version: '2'

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx
    ports:
      - "443:443"
    restart: always

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb
    ports:
      - "3306:3306"
    restart: always
