#version: '2'

services:
  nginx:
    container_name: nginx
    env_file:
      - .env
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
        # - DEBIAN_VERSION=${DEBIAN_VERSION?Variable DEBIAN_VERSION not set}
    image: nginx
    ports:
      - "443:443"
    depends_on:
      - mariadb
    restart: always

  mariadb:
    # mem_limit: 1gb
    container_name: mariadb
    env_file:
      - .env
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    restart: always
    volumes:
      - mariadb:/var/lib/mysql

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: requirements/volumes/mariadb
      o: bind
