#version: '2'

services:
  nginx:
    container_name: nginx
    env_file:
      - .env
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
        # - DEBIAN_VERSION=${DEBIAN_VERSION?Variable DEBIAN_VERSION not set}
    image: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: on-failure
    volumes:
      - wordpress:/home/login/data
    networks:
      - all

  mariadb:
    # mem_limit: 1gb
    container_name: mariadb
    env_file:
      - .env
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    restart: on-failure
    volumes:
      #- mariadb:/var/lib/mysql
      - mariadb:/home/login/data
    networks:
      - all

  wordpress:
    container_name: wordpress
    env_file:
      - .env
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    restart: on-failure
    volumes:
      # - wordpress:/var/www/html
      - wordpress:/home/login/data
    depends_on:
      - mariadb
    networks:
      - all

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: requirements/volumes/mariadb
      o: bind

  wordpress:
    driver: local
    driver_opts:
      type: none
      device: requirements/volumes/wordpress
      o: bind

networks:
  all:
    driver: bridge

